locales/English/help.php

English help page had old sourceforge.net link.  Project now resides on
GitHub.

Added GitHub to English Help Page

---

install/1.37-1.38/update.sql

Adds `objects/useroptions.php`, an object for handling user options. User options are stored in their own table, which is only populated when users save options (so it is lazily created for existing members). They are loaded when a `User` object is created. In addition to being part of the user object, options are also exposed to the client through `useroptions.php`, which produces a json object that describes a user's preferences for use in javascript.
The colorblindness fix is applied client side, depending on the user's options. It is triggered when the map changes, and replaces the map image with an appropriately adjusted version. Additionally, press is displayed with the country's name at the start of the message. Thanks to @Sleepcap for the suggestions and inspiration of this …

A mechanism for user options, and client side colourblind fix

---

gamepanel/gamehome.php
objects/game.php

Decided to just use a switch statement for generating the abbreviations for the pot type rather than make database updates.

Fix for #149: Expose pot type in small gamepanel view on home page

---

board.php

Delayed the creation of the header to include the name of the game.
Tested under Firefox and Opera.

Issue #164

---

forum.php

Changed message upon creation of new thread to refer to the issue tracker on GitHub.
Tested under Firefox and Opera.

Issue #174

---

forum.php

This logic will force successful forum replies to issue a redirect after successful submission with "reply=success" as a url parameter (this parameter enables the "Reply posted successfully" message to show up).  Any refreshes of the page will have this success message stay intact, but no messages will be reposted.

Forum reply redirects to eliminate double post bug

---

board.php

The chat panel is now visible to every visitor of the game, once the game started.
**Test cases, checked and passed**
* Tested under Firefox
* Created a game with no chat restrictions.
** Mods/Admins see the global tab and are able to write messages.
** Participants see all tabs and are able to write in every tab.
** Spectators (or Observers, they don't have to select "Spectate") can see the global tab but nothing else. They are not able to write in the global tab.
* Created a game with no ingame-messaging
** Mods/Admins are able to see the global tab and write in it.
** Participants are able to see the global and notes tab, but can only write in the notes tab.
** Spectators are able to see the global tab
**Test cases not checked**
* A game with global press only
**Possibly …

Bugfix #201

---

lib/message.php

Changed the regex for detection of the points icon to only detect "(d)" [was "d" and "points"].
Attached image shows new outputs. The row with the symbols have been "1(D)", "1(d)", "1 (D)" and "1 (d)"

Conversion of (D) into points symbol

---

javascript/orders/form.js
javascript/utility.js

Tested under Opera and Firefox
* Opera and Firefox
* Leaving any page with unsubmitted text will still trigger the warning
* Leaving the board with unsaved orders will trigger a warning about unsaved orders
* In case the user selects to leave the page with both unsaved orders and unsubmitted text only one warning (in my case unsaved orders but this does not seem to be guaranteed, according to documentation of addEventListener) will be triggered (even if the user decides to leave the page)
* Special case Firefox
* No custom text is displayed leaving the user without knowledge why the page requests the navigation
Untested browsers: Internet Explorer (according to specifications of addEventListener some IE versions need to call attachEvent), mobile browsers (according to specifications of …

Display message when leaving page with unsaved orders

---

install/1.42-1.43/readme.txt
install/1.42-1.43/update.sql

The code version had been updated, but the database's had not yet been. This change brings the database up to speed. The only change necessary was the version number itself.

Update database to version 1.43

---

profile.php

Some of these links on profiles are not confirmed and make looking at
profile pages on phones dangerous for mods and admins. Some like mod
report features are not used at all and just clutter the options. The
forum moderator links are no longer needed after the migraion to the new
forum, and are now misleading.

Removing Dangerous and Unused Mod links

---

css/gamepanel.css
gamecreate.php
gamepanel/game.php
locales/English/gamecreate.php

Removing text referring to a game password and replacing it as an invite
code so people no longer think they need to enter their account password
to join a game. Also noticed the country progress color bar was missing
a css 2% margin making it stick out so fixed that too.

Changing Game Passwords to Invite Codes

---

css/desktopOnly/gamepanel.css
css/gamepanel.css
gamepanel/gameboard.php
gamepanel/member.php

The current CSS tags are shared across various different elements making
CSS updates nearly impossible I've split out some of the various
progress bars based on name/location in the game page. Adjusted bar
lengths, and tested on desktop and mobile views, classic, ancient med,
and 1v1 to ensure variant styling wasn't impacted.

Adding distinct CSS tags

---

index.php

Removes politics from forum preview, and lets mods or members hide a
thread from the preview using HIDDEN in the thread title.

Remove Politics from Preview

---

gamepanel/member.php

The admins and mods have a long standing rule that you cannot TD a game
you are playing in, so we're allowing TD's to break anon so they can
actually use tools like country swap already available to them.

Allow the TD of a game to see who's who even in anon games

---

gamemaster/members.php

Previously if a player got 18 centers in the fall the game would declare
them the winner before the retreat phase. Now if there is a retreat
phase, the game will wait and check for the winner after retreats are
done.

Check for retreat options before win

---

gamepanel/member.php
gamepanel/memberhome.php
objects/basic/set.php

After the additional anon protection various members complained it was
now difficult to easily see who had retreat or build options on large
maps. This change will replace the !!, !, grey check, and green check
options with the old forum lock icon to indicate who has moves both in
game and on the member home preview. Only game directors will be able to
see through the lock on the home preview (since TD's spectating games is
quite normal) whereas mods spectating games should not need to see
through (I'm planning a future enhancement to hide members in anon games
for mods who are spectating the game).

Various Anon Updates

---

lib/html.php

Specifically:
- Malformed URL sent the user to a page where the PM could be viewed, but all links from that page were broken.
- The notification text included an online indicator, which the site no longer displays anywhere in order to protect anonymity.

Fixes bugs in the header notification of new forum PMs.

---

gamepanel/member.php

The memberBar is called from an external file, which causes various
issues with private variables since they aren't set in that file's
instance. For now, this fix accounts for all cases and renders checks vs
locks for anon for both mods and non mods.

Add isset to isNameHidden

---

locales/English/user.php

Anyone who went to their settings page if they had active muted countries got this error. 
Catchable fatal error: Object of class __PHP_Incomplete_Class could not be converted to string in /var/www/webdiplomacy.net/public_html/global/error.php on line 107
I was able to narrow the problem down to the specific line:
$LoadedVariants[$variantID] = libVariant::loadFromVariantID($variantID);
The people on google who had the same problem discussed an issue around
serialization after PHP upgrades to version 7 which was just done.
Looking into the failing function libVariant::loadFromVariantID I see it
is also doing serialization, which is far out of my skill set in php. I
did confirm that the other places on the site that use this function are
working as intended. So for the time being I …

Emergency Fix for Issue from PHP Upgrade

---

javascript/orders/phaseDiplomacy.js

This is a fix in phaseDiplomacy.js for a rarely occurring error case. The only consequence on webdip despite the error message in the console is a disabled "Ready"-Button even though all entered orders are completed (as the script stopped working before enabling the button). But it is still possible to save and ready after that. Hence this probably was not detected yet. However, on vdip the "Save"-Button is disabled during the entry of an order, as well, causing both buttons to be wrongly disabled. So a fix is a bit more important there.
Cause:
In phaseDiplomacy.js, line 47, it is wrongly assumed that a supported-to-territory has a convoy group (i.e. can be convoyed to). The fix just adds an additional check here. 
Steps to reproduce the error:
Create the situation of to coastal armies …

Fix for a rare error in phaseDiplomacy.js

---

profile.php

Add a link on all the old forum profiles to the new forum profiles of a
user. If the user does not have a new forum profile nothing is shown. If
the server database does not have the new phpbb tables, nothing is
shown.

Add link to new forum

---

admin/adminMultiFinder.php

Remove private game only matches from the advanced checkbox option.
There's nothing wrong with friends playing private games together and it
makes so much noise that this option is currently useless.

AdminCP Cleanup - Update multi finder to remove private game matches

---

admin/adminActions.php
admin/adminActionsForms.php
admin/adminActionsForum.php
admin/adminActionsRestricted.php
admin/adminLog.php
admin/adminStatusLists.php
css/global.css

Fixing cluttered emergency actions that previously was too easy to hit a non confirmed action on a phone. Since these included wiping admin logs it presented a serious data loss risk. Clearing log actions were removed from this section.
Moving sync forum likes to forum mod status
Moving donator perks to admin only
Fixing control panel logs to break words and to resize to phones.

Additional Cleanup of AdminCP

---

admin/adminAdvancedAccessLog.php
admin/adminMultiFinder.php
admincp.php
css/global.css
global/definitions.php
install/1.44-1.45/readme.txt
install/1.44-1.45/update.sql

This will add a new moderation tools to allow mods to quickly find new cheaters who have just joined the site. Adds a new table to the site to allow for saving the results of heavy cost queries normally run from the multi finder. Adds an insert/update to this new table every time the multi finder is run to log the mod and time of the run to be displayed on the user profile for mods only in a future update.

Add Advanced Access Logging

---

admin/adminActions.php
gamemaster/member.php

There were several scenarios where a live game could have a player leave or be removed without the min bet on the game being reset, which would cause the game to not have a join button even if it wasn't full.
1. a Mod bans a user in a full pre-start live game.
2. a player in a full pre-start live game leaves.
This has been causing multiple live games to be non-startable despite enough interest.
Adjusted by adding a call to the resetMinimumBet function. This isn't an ideal fix cause it won't be apparent for people working on game code but should work for now.

Fix Vanishing Join Button

---

gamemaster/game.php
gamemaster/member.php

The reset min bet function was never right for being called as a user was being removed from a pre-start game. The way the logic worked meant the user count wouldn't refect the real user count in the members table. Only discovered when the resetminbet function began getting called when it was initially supposed to. Count is now being pulled direct from the db to avoid state issues.

Fix 10 year Issue

---

detailedSearch.php

Account for the fact that games can have leading or trailing white space in their name by trimming the comparison in the where clauses against the name until that naming bug can be fixed.
Change the timeJoined display to show Month Day Year instead of time on user search.

Advanced Search Updates

---

gamelistings.php
gamemaster/misc.php
gamesearch/searchItemSettings.php

Rename hover over text on "Joinable" to inform that it's public games only.
Redo wD_Misc GamesOpen query to correctly pull the number of joinable games. Old query was incorrect.
Rename "Hours per phase" in search criteria to "Time per phase" since all phases aren't hours like live games and 10 day games.

Fix game search issues

---

contactUs.php
css/global.css
lib/html.php
locales/English/contactUs.php
locales/English/credits.php
locales/English/help.php
locales/English/rules.php
locales/English/tournaments.php
tournaments.php

1. Updating Rules content and style
2. Making a contact us page which will be altered in the future to have a direct contact form to email mods from in site.
3. Making a tournament page with info on tournaments
4. adjust credits page to have relative links.

Revamping Help Section Pages

---

index.php

The live game check query was taking .22 seconds to render due to the new or hitting finished games. Adding in phase checks on an indexed field to reduce that check set to rerender in 0.00 seconds.

Adjust Query for Speed

---

detailedSearch.php

Search games by user was going slow due to a nested select instead of an inner join. Dropping from 3.2 seconds to .4 for users with 500+ games.

Speed up Search

---

css/desktopOnly/home.css
css/home.css
facebook/css3/home.css

Prevent the 3rd column on home to overflow when members are in variants like Chaos.

Prevent Game Stats Overflow

---

admin/adminActions.php
contactUsDirect.php
global/definitions.php
install/1.47-1.48/readme.txt
install/1.47-1.48/update.sql
objects/user.php
profile.php

Allow 1 automatic pause of all games for players who have completed at least 10 games and have not used an automatic pause in the last 6 months. Adds a mod tool to reset the time if a player presents a valid excuse or the option to ban members from using this tool at all. Mods can see on the profile page if a member qualifies for an automatic pause or not. This tool pauses the games and then emails the moderator team so they can follow up and post an explaination in the game chat.

Add Emergency Pauses

---

gamesearch/searchItemSettings.php

excusedmissedturns is not ambiguous in specific cases of game search, adding alias to it.

Fix ambiguous column error

---

admin/adminActions.php

Currently the way that cancelling a game works is slightly broken which means cancelling games doesn't make a log in the admin log. I hard-coded a work around for this, with more details being added into the log.

Make a log in the adminlog when cancelling games

---

gamepanel/game.php

Fixes https://github.com/kestasjk/webDiplomacy/issues/222
When a game is unjoinable, it now will show a reason for why the game is unjoinable, whether it be unreliability, too poor, or a temp ban. Tested to also make sure that this does not show unless you are logged in.
Also, the minimum reliability number was only showing up if you had enough points to join a game, so I moved around some of the nested if statements so that it would show regardless. The whole nested if statements, isJoinable function, and the whole layout is a bit messy.

Add reason when you cannot join a game

---

board/chatbox.php

After changing the message archive on chaos, it shortened the chatbox back down to 20 messages. This will increase the chatbox for all variants to 50, a more reasonable number.

Change default messages shown to 50 in chatbox

---

gamemaster/game.php

Prevent live games from recording missed turns as same period excused because people have been abusing this to continuously take over their own CD position to extend phases.

Excused turns adjustment

---

css/desktopOnly/global.css
css/global.css
global/definitions.php
objects/database.php

Currently the footer spans width 100 of the possible page and can blow up horribly when there are many "bad queries". Centering it, maxing it at 800px.

Fix Footer for Mods

---

gamepanel/game.php

Makes it so that you can see the Variant name Classic on the gamepanel, instead of leaving it blank.

Show Classic identifier on game panel

---

admin/adminActions.php
gamemaster/game.php

Stop players in the left status from continuing to rack up Missed Turn records.
Add mod tool to recalculate a player's RR instantly.

Fix Excused Missed Turn Bug

---

install/1.50-1.51/update.sql

when trying to run the update script it would cause errors as the engine statement requires the semi column to be present

missing semicolumn causing error while trying to update

---

gamepanel/members.php

Allow all members to see the list of CD's during the course of the game after the game has finished.
Fix bug preventing mods from seeing CD users in their own finished games.
Fixes https://github.com/kestasjk/webDiplomacy/issues/226

Show CD's After Game End

---

board/chatbox.php
board/info/messages.php

Redoes the paging for archived messages in a game to be uniform with the other paging changes made recently. Also adds an option in the archived messages to filter down to just a single country, or global, or notes.
Also fixes issue https://github.com/kestasjk/webDiplomacy/issues/200 from 2015, after realizing that the messaging ordering gets switched several times in order to display the recent messages in the correct place.

Message Archive Paging

---

tournamentScoring.php

Created a scoring page to use in conjunction with the tournament stuff jmo is doing. Allows users to select tournaments from a dropdown menu. Once a tournament has been selected, shows a table with all participants in the tournament, and their scores, round by round. Each table heading can be selected to sort by, and rankings populate when sorting by a specific round.
When the user is a TD director for that tournament, or a mod, the table will have number inputs for each score, with an update button at the bottom, so that tournament scores can be modified.

Tournament Scoring Page

---

gamelistings.php

Prep work for the upcoming tournament page jmo and I are working on. This allows a parameter "tournamentID" into the gamelistings.php search page, which filters down to only games in that tournament.
When searching among tournament games, the "My games" and "Joinable games" filters are dropped, and a "Round" filter is added.

Alter gamelistings to be able to take in a tournament id

---

locales/English/user.php
usercp.php

Due to a severe problem in the variants code, variants cannot be loaded from all pages, including the user page after the php upgrade to 7.0. I partially worked around this to at least display games that have country mutes in them.

Update Mute Settings

---

install/FullInstall/fullInstall.sql

Small error I found during the setup of my new webdip installation.

Missing ";" prevented a clean fullinstall

---

profile.php

If a user had a missed turn in a game that had been cancelled the RR display page was breaking. Fixing the variant setting and variant related information to be inside a conditional if the game still exists and just showing base info on the cancelled game's missed turns.

Fix Bug on RR Display

---

tournaments.php

Move loading the variant info to non finished games only to speed up loading the finished tournaments tab. Adjust table columns shown for finished tournaments to more useful information.

Adjust Tournament Code

---

contactUsDirect.php
lib/html.php
locales/English/faq.php
tournaments.php

Link on tournaments.php goes to tournamentInfo.php. Forum header needs to be adjusted.

Removed Tournaments Info from header, linked on Tournament tool

---

map/drawMap.php

Small fix to display the correct font instead of HTML-code in the final map of a game.

Fix the display of HTMLcode in the final map of a game.

---

admin/adminActions.php
gamemaster/game.php
gamemaster/gamemaster.php
gamemaster/members.php
install/1.55-1.56/readme.txt
install/1.55-1.56/update.sql
objects/user.php
profile.php

Adjust RR so that unexcused missed turns operate differently for live games. Live game players have 3 unexcused missed turns in a 28 day period that can be missed without a temp ban. After that any unexcused missed turn will result in a 24 hour temp ban. Any further after that day are also just 1 day temp bans. RR hits for unexcused missed turns are the same 11%. But for live games the 6% added penalty will vanish in a week, and the remaining 5% will be gone in 28 days. This should help live game players not be impacted as negatively by missed turns. These unexcused missed turns in live games will NOT count against the yearly total for temp bans for normal missed turns. The RR page has been updated to show how this extra penalty works only if you have live games with missed turns. This …

Adjust RR for Live Games

---

gamemaster/game.php

Limit the time a game can be extended with a single extend to 24 hours. Games that have phases shorter then 24 hours will only be extended to their full phase length. This should allow players suitable time to come back from a short emergency without losing their position in games with a delay, or should allow replacements time to get up to speed in games without delays.

Limit Game Extends to 24 Hours

---

profile.php

Issue #210
Reorder the game stats display to more accurately display
the stats that show how good a player is at the game.
The new order:
Wins > Draws > Survivals > Defeats
Playing, Civil Disorders, and Civil Disorders taken over are in a separate grouping as they don't directly reflect on a player's skill, more their reliability.

Reorder "Game stats:" display

---

global/definitions.php

Other contributors forgot to update the versions after js and css changes, adjusting for that.

Updating Versions

---

admin/adminActions.php
gamemaster/member.php
objects/user.php

Adjust points so that bots will never have points taken or awarded. Keep the calls to the user function that controls point distribution because those functions control the member and game table records being updated for bet and pot. So a bot's "bet" in a game will always be 5 points and when they leave a game it will always remove 5 points from the game pot. This is because games with bots playing will have to be unranked, which will be forced in game creation options in another PR.

Adjust Points for Bots

---

api/responses/unordered_countries.php

The API indicates that defeated powers are missing orders, so the bot needs to retrieve the game to figure out that the power has no orderable locations.
This PR fixes the issue by only returning 'Playing' powers.

API - Only returned powers who are still playing

---

gamemaster/game.php

The way that votes are applied does not fit very well with bots. This fix will get around this by checking if a game has only bots left every single time the game processes and force drawing the game when appropriate.

Fix bot voting

---

gamemaster/member.php

A weird edge case happens for member vs bot games. If a game has been created but not started (due to gamemaster breaking), and then someone leaves a bot game, and a different user joins that game, then country assignment gets messed up.
This will auto cancel any member vs bot games when someone leaves the game, which should prevent this from happening.

Bot cancelling

---

javascript/board/model.js
javascript/orders/phaseDiplomacy.js

This is fix to a similar issue as in #357 which leads to the JS code crashing when orders involving convoy paths are set in a certain order in certain situations. This temporary locks the Ready-Button on WebDip. On vdip, the Save-Button is locked, too, making the bug more visible over there.
**Steps to reproduce the problem:**
I encountered one way today, when I entered first A Ser S A Rum -> Bul (while there was a fleet in BLA) and after that I changed the order to A Ser -> Rum.
**Cause:**
As in #357 the cause is related to the code in javascript/orders/phaseDiplomacy.js that checks if a convoy path has to be provided to the server. In that part of the code, the variable Unit.convoyOptions is used to determine if the set order can only be fulfilled for a convoyed unit. In that case a …

Fix for problems with convoy code in phaseDiplomacy.js

---

locales/English/help.php

Previously the privacy policy was just on the server version of the file since not all sites use one downstream but maintaining it that way has been a hassle so moving it onto the repo.

Move Privacy Policy to Git

---

admin/adminActions.php
admin/adminActionsForms.php
admin/adminActionsRestricted.php
admin/adminActionsSeniorMod.php
admin/adminStatusLists.php
global/definitions.php
install/1.64-1.65/readme.txt
install/1.64-1.65/update.sql
install/FullInstall/fullInstall.sql
objects/user.php

Splitting the moderator type into 2 types. The goal is creating a new basic moderator type where new moderators have access only to tools needed to complete basic jobs. More complex or dangerous tools used by senior moderators have been moved into the senior moderator class. The inheritance has been changed so that all senior moderators will by default have access to all forum moderator tools. New admin tools have been included to manage senior moderator status, and senior mods are displayed on the status page in the admincp.
**IMPORTANT NOTE: When adding this code on a live diplomacy site all current moderators will lose access to multiple tools until an admin gives them the senior moderator role. Admins will be default have access to all senior moderator tools and will not lose …

Adding Senior Mod Type

---

admin/adminActionsRestricted.php
config.sample.php
gamemaster/game.php
ghostratings/calculations.php
global/definitions.php
install/1.65-1.66/readme.txt
install/1.65-1.66/update.sql
install/FullInstall/fullInstall.sql

This code attempts to integrate Ghost Ratings into webDiplomacy. Includes code that takes in game data and calculates GR adjustments. Integrates this code so that when games finish, GR is automatically adjusted. Provides an admin tool to backfill GR in batches. Has multiple table in the database to store GR historical data. This includes a game by game, user by user accounting of each GR adjustment (very detailed), as well as a month by month accounting of each user's GR (big picture). The config file has been adjusted to allow for customization of these GR calculations. You can create your own categories and filter by variant ID, press type, phase length, scoring type, etc.
As this is a large change, thorough testing and reviewing is needed. I have conducted a lot of testing on the …

GR Integration

---

locales/English/faq.php
locales/English/intro.php

As per the discussion in Issue  #335 , this commit makes some minor changes to the Intro to Diplomacy page, adding some clarifications to common misconceptions new players have about the support hold order. The changes are minor, since there was resistance to making the page overly complex.
Also adds a link to the official Avalon Hill rulebook on the intro page, and corrects a broken link to the rulebook on the FAQ.

Minor additions to into, and fixed broken FAQ link

---

.gitignore
README.txt
objects/silence.php
register/processUserForm.php
variants/variantData.php

* Updates the README to be clear about the PHP version support
* Updates the README to suggest using FullInstall as opposed to each mysql file during setup
* Fixes constructors that are named as the class (this causes PHP deprecation warnings)
* Fixes uninitialized variable in processUserForm.php

Fixes for getting started doing development

---

botgamecreate.php
locales/English/gamecreate.php

"Play A Game Against Bots" → "Play a game against bots"
"Play A Game Against Humans" → "Play a game against humans"
It's a link, not a page title or header.

less unnecessary and excessive capitalization

---

api.php
api/responses/game_state.php
api/responses/message.php
lib/gamemessage.php

This PR updates how timestamps are passed around for messages. It also adds a missing SQL COMMIT and fixes a `count()` callsite that was causing issues for some reason by following format used at similar callsites elsewhere in the codebase
Manually.
I have a local instance of webdip running on Apache. I created a game. I then sent messages around between mock accounts I created, and then I confirmed they were received. I used Postman to confirm that message sending API endpoint correctly returns the timestamp.

Return timesent in api

---

api/responses/game_state.php
api/responses/vote_message.php

In games with public draw votes, it would be nice if the API endpoint `game/status` returns the current votes of other players. To this end, I add a field `publicVotes` that is empty when draw votes are hidden and otherwise maps country IDs to vote statuses. Additionally, let's return the draw type for the game  (`drawType` in `wD_Games`) and the time until the next phase (`processTime` in `wD_Games`).
Secondly, it would also be nice to surface vote history with timestamps (in public draw vote games). When a player submits a draw vote themself, they can see a message "Voted for Draw" in their personal message history, along with a timestamp. I should also be able to see something similar for other players' votes:
```
"phases": [ 
...,
{
...,
"publicVotesHistory": [
{
"vote": "Voted for …
```

Show votes in game/status

---

api.php

We currently log votes sent in the web UI to the message history to keep track of when people called for different kinds of votes (https://github.com/kestasjk/webDiplomacy/blob/master/board/member.php#L142-L144). This can sometimes be useful context when discussing previous draw attempts. 
However, we do not do such vote logging by message history for votes sent by API. Let's fix that
Manually

Log API votes in message history

---

api/responses/game_state.php

Currently, the API endpoint `game/status`, which info about game state such as message history, does not surface messages send to the global messaging channel. Let's fix this.
Manually.

Include global messages in API game/status

---

api/responses/game_state.php

In the UI, we can see whether or not other players have readied and/or saved their orders. We should also be able to see this via the `game/status` API endpoint.
Manually

Surface order readiness in API

---

api/responses/game_state.php

The status json should surface configurable settings about games. This PR surfaces phase length (in minutes).
```
{
...,
"phaseLengthInMinutes": "4320",
}
```
Tested manually on a local server

Surface phase length

---

gamecreate.php

This adds Cold War to the Game Creation page's code that forces 1v1s to only create unranked, 5pt bet game, to prevent point farming. 
I had forgotten to add this when first adding the Cold War files.

Cold War games forced to unranked 5pt bets

---

gamepanel/game.php
gamepanel/gamehome.php

Even though spectation was possible in the beta UI, there were no links to make it obvious how to do it. Added the links.

Add links for beta spectation
