objects/database.php

This patch is an initial fix for the mysql functions being deprecated in php 5.5. It just changes the `mysql` functions to use their `mysqli` counterparts.
At a later date, we should probably use the improved features of this extension (prepared statements etc).
This patch will cause webdip to depend on php 5.0 or higher.

Changed mysql functions to mysqli functions

---

locales/English/credits.php
locales/English/faq.php

spelling and typos fixed

---

admin/adminActions.php
admin/adminActionsTD.php

Change description for issue #126

Update adminActions.php Issue #126

---

locales/English/faq.php

line 127 of locales/English/faq.php corrected "his the panic button" to "hits the panic button"

fixed spelling error

---

locales/English/credits.php

First submitted pull request for fixing issues!  Let me know if there is official testing I can/should submit.

Fix for #62: Automated moderators list for Credits page

---

profile.php

Added word-wrap:break-word style to list item to wrap long home page URLs

Fix Issue #218

---

objects/database.php
objects/notice.php

Kestas's code to prevent deadlock problems that was never checked in.

Preventing Deadlocks

---

board/info/messages.php
css/gamepanel.css
css/global.css
css/home.css
gamepanel/game.php
lib/html.php
locales/English/validationForm.php
locales/Italian/validationForm.php

This is a build I made to better support mobile devices. I was kinda sick and tired of having to zoom in constantly and how most things were very hard to do on a mobile device. This branch adds full mobile support, focused on CSS changes only. There were a few non css files that I had to edit because of inline styling issues.
Everything is working properly in all major browsers:
Tested in:
Edge & IE11
Chrome 49
Safari 10
Firefox 48
No github issue, just want to make the site/project better!
Let me know if there are any concerns or questions!

Better mobile support

---

css/desktopOnly/gamepanel.css
css/desktopOnly/global.css
css/desktopOnly/home.css
css/desktopOnly/notices.css
javascript/utility.js
lib/html.php

This adds a client side toggle between desktop and mobile css. 
Unfortunately this solution means that CSS files will have to be duplicated between desktop and mobile supported versions. May not be the best solution but this will solve the problems some people have with the new mobile layouts. It will also allow you to have it turned off on your home pc and turned on on your phone.

Mobile desktop toggle

---

variants/Modern2/install.php
variants/World/install.php

Modern & World Bug Fixes

---

gamemaster/member.php

Coding done by !, sent to me to make the pull request.

Unranked Survival game end message fix

---

gamemaster/member.php

Bug Fix for previous update

---

admin/adminActions.php

Fixing reallocate countries and alter messaging type

Updating Admin-CP Tools

---

locales/English/help.php

Clarified wording, added better contact info. Improved ordering.
(I'm not 100% sure I did the php mailtos correctly. Can someone check?)

Wording update for help.php

---

gamepanel/member.php

Fixing an issue where defeated countries counted as missing orders.

Fix anon bug

---

javascript/Color.Vision.Daltonize.js

Fix for #324 
Allows map to scale properly on all screens with colorblindness feature enabled

Fix colorblind scale

---

board/chatbox.php
javascript/message.js
lib/html.php
message.php

Send chat messages in the background, without having to reload page

Submit in game messages without page reload

---

gr.php
locales/English/rules.php

Addition of new rule and adding the gr.php file to git which was lost
during the last server migration.

Rules and GR

---

admin/adminActions.php
gamecreate.php
gamemaster/members.php
gamepanel/game.php
global/definitions.php
install/1.43-1.44/readme.txt
install/1.43-1.44/update.sql
lib/html.php
objects/user.php

This will add a vDip moderator tool that allows temporary bans on accounts, which will eventually be used to automatically issue temporary bans during CD's.

Add mod tool temp ban

---

admin/adminActions.php
gamecreate.php
gamemaster/members.php
gamepanel/game.php
global/definitions.php
install/1.43-1.44/readme.txt
install/1.43-1.44/update.sql
lib/html.php
objects/user.php

Allow quick game swaps by moderators.

Add mod tool country replace

---

.gitignore
lib/html.php

The former allow for unofficial rating systems, and aren't necessarily desirable for a new installation.
The later is a broken variant that remains on the server so as to not break old games.
Both exist on the server currently, so this allows us to bring it in line with GitHub.

 Add GR script/output and KnownWorld_901 files to .gitignore

---

locales/English/intro.php
locales/English/rules.php
locales/English/validationForm.php
register.php
register/processUserForm.php

Update registration links to the new forum, update text to be more
welcoming/useful. Update rules to reflect new tournament rules. Update
intro to explain points and RR.

Various Updates to Rules and Registration Text

---

admin/adminChatAnalyser.php
admincp.php

Includes significant cleanup alteration and anon checks.

adding mod press tool from vDip 

---

admin/adminLog.php
admin/adminStatusLists.php
admincp.php
css/global.css

Updating the global css to have custom css tags for the admincp and restyling several of the admin cp tabs. Fixing minor issues in the display of status lists as well.

AdminCP Cleanup

---

admin/adminAdvancedAccessLog.php
admin/adminChatAnalyser.php
admin/adminMultiFinder.php

1. Fix a bug I introduced to the multi tool that showed all games as active in the results list.
2. restyle the press pull tool and remove un-needed variables and code blocks.
3. change the accesslogs page to show most recently joined users on top vs bottom and increase max pull size to 1,000 days since performance was faster then expected even on webdip.

Additional AdminCP Updates

---

gamemaster/member.php

This file doesn't have Variants defined so it needs to be loaded and then set the game equal to the Variant game instance. Same as in the reset min bet use in the admincp.

Fix Missing Join Button

---

css/global.css
detailedSearch.php
lib/html.php

Adding a new advanced search tool to the site that allows for complex searches on games and users. Currently only going to be pushed live for mods to test load balances and a couple features that will only work live.

Add advanced search

---

detailedSearch.php

Add advanced search updates

---

detailedSearch.php

A few minor fixes based on mod testing

Update detailed Search

---

detailedSearch.php

remove some debugging outputs and adjust donator results.

More Minor Adjustments

---

detailedSearch.php

Show # of spectators and add it to the sorting option.

Add Watched Count

---

css/global.css

update font size

---

css/global.css
detailedSearch.php
lib/html.php

Make Advanced Search live to all users and adjust the header so an entire row of links are accessable under the logo.

Make Advanced Search Live

---

lib/html.php

Force JS version change for recent js changes.

Force JS Version Change

---

css/global.css
detailedSearch.php

Allow people to search for a given user's games and check for games between a user and themselves. Finished games only.
Update the "show only joinable games" in the game search to filter out "Pre-start" games. 
Refactor some of the css tags and code, add more comments.

Enhance advanced search

---

detailedSearch.php

Error of double variable declaration didn't show up in local env, so live server must have additional strict checkes somewhere.

Fix Live Error

---

objects/user.php
profile.php

Show mods the last time a user was investigated, if ever, and by who.

Adding Mod Info to Profiles

---

css/global.css
objects/user.php
profile.php

1. Fix username to wrap on left column of profile.
2. fix moderator disclaimer link to wrap
3. add Classic and Variant stats to the profile page.
4. Add hover over that explains what the different "ranks" mean...somewhat, at least more then now.

Profile Page Improvements

---

profile.php

Profile Update

---

css/global.css
halloffame.php
locales/English/faq.php

1. Restyle FAQ to allow more then 1 open question
2. Update FAQ info, there were a lot of wrong answers on it.
3. Update to have links to new forum
4. Update HoF to be restyled
5. Update HoF to highlight you in red if you're on the list.

Update Help Pages

---

css/global.css
locales/English/credits.php

Removed the columns from the credits page and rearranged the information displayed so that it can be easily accessed and updated with relevant information as necessary without being more cluttered. Added basic styling for the new credits page as well but without a local environment to test on I cannot see it, so the style changes may not be quite right yet.

Removed columns and changed format to declutter the credits page

---

contactUsDirect.php
css/global.css
lib/html.php

Allow users to fill out a form to send a detailed problem email to the mods will all the information mods need.

Add Direct Contact Us Page

---

contactUsDirect.php
gamepanel/gameboard.php
lib/html.php
locales/English/contactUs.php
locales/English/help.php

Make the contact us direct live across the site.

Make direct contact us live

---

css/global.css
datc.php
locales/English/datc.php
locales/English/developers.php
locales/English/intro.php
locales/English/user.php
usercp.php

Update settings, intro to diplomacy, developer, and datc tests pages to modern styling. Minor content corrections.

Restyle Multiple Pages

---

css/global.css
locales/English/user.php

Minor Fixes

---

contactUsDirect.php

attempting to fix state issue on a variable.

Try and fix state issue

---

contactUsDirect.php

update to remove live check

---

contrib/phpBB3-files/styles/AllanStyle-SUBSILVER/template/overall_header.html
css/desktopOnly/home.css
css/global.css
css/home.css
facebook/css3/home.css
gamepanel/gamehome.php
global/definitions.php
index.php
install/1.45-1.46/readme.txt
install/1.45-1.46/update.sql
internal_error.html
javascript/desktopMode.js
lib/html.php
missing.html
objects/notice.php

1. Add defeated games section to split up active playable games and games you're beaten in.
2. Add toggle to hide/show notifications for games in the home page.
3. restyle old and new home forum sidebar
4. add css cache busting to global.css and home.css
5. update upcoming live games to include joinable live games as well in case someone goes into CD.

Home Page Updates

---

css/global.css

Should not have any impact on the functionality of the button

Dummy link styling for new enable/disable notices button

---

css/global.css

increase from 12 to 14 for media views

update media size

---

css/global.css
css/home.css
index.php
objects/notice.php

1. Adjust the style of the games notice column
2. Fix a bug that kept pm's on the notice section at 60% width on media view
3. Remove April Fools "mood" colors.

Finish Index Styling

---

board/chatbox.php
board/orders/orderinterface.php
css/desktopOnly/gamepanel.css
css/desktopOnly/global.css
css/desktopOnly/home.css
css/desktopOnly/notices.css
css/gamepanel.css
css/global.css
css/home.css
css/notices.css
gamelistings.php
gamemaster.php
gamepanel/gameboard.php
gamesearch/search.php
index.php
install/1.43-1.44/update.sql
javascript/cacheUpdate.js
javascript/timeHandler.js
lib/html.php
locales/English/gamecreate.php

1. Restyling everything still on the old font
2. restyling game page look
3. fixing styling issues in desktop view on phones (somewhat, more will be needed)
4. fixing broken sql install script.
5. fixing broken link to avalon hill's page on diplomacy
6. Adjusting time javascript functions to keep them from breaking IE 11 and Safari 9 users.
7. Prevent the onlineUsers.json file from being updated. Will eventually be able to be removed.
8. Impliment framework code for a new menu div, adding it commented out to allow other developers to see before it's live.

A number of housecleaning fixes

---

css/desktopOnly/global.css
css/global.css

Adjust disabled button shape/color/disable pointers on hover over.

Adjust disabled button style

---

gamepanel/gamehome.php

Remove "stop spectating" as an option for games you aren't in.

Fix Home Spectate Option

---

profile.php

Profile-Fix

---

detailedSearch.php

Allows users to search for finished games from a user by username, rather than user id. Mostly pulls from existing code, copying much of the search by user id code with changes in variable names and other adaptations. Basically I pulled the beginning part of the search for user id by username code and stuck it on the front of a copied version of the search by user id code, then smoothed it over and made sure everything worked out. This is my first pull request, so please give me feedback on what I should be doing better. Thanks!

Search by username

---

gamelistings.php

Change the query to cut run time by 90%.

Speed up Games Tab

---

css/desktopOnly/global.css
css/global.css
detailedSearch.php

For the search page, it adds paging to the results. Also adds clickable headers in the table which will resort the results by that header. Clicking on the header of the category it is currently sorted by will change the sort type (ascending vs descending). Also did a few minor changes, such as renaming a few sorting drop down options to be more uniform with the column headers. Fixed a bug that caused the game name sorting option to actually sort by username.

Search paging

---

global/definitions.php
install/1.46-1.47/readme.txt
install/1.46-1.47/update.sql
javascript/orders/order.js
objects/useroptions.php

Create a user option to sort the dropdown options when loading possible orders. Defaults to sorting alphabetically, with options to revert to no sort and to push all the via convoy orders to the bottom (while sorting alphabetically still).

Create a user option to sort possible orders in dropdown

---

lib/html.php

Update the js version number to force refresh

Force JS refresh

---

gamemaster/game.php

Addresses issue 301. When renaming for uniqueness, the new game name will now be guaranteed to stay less than or equal to 50 characters so that it fits in the database.

Fixed game name uniqueness/length bug

---

css/home.css

Fix mobile view for game previews

Fix mobile view

---

contactUsDirect.php
css/desktopOnly/global.css
css/global.css
detailedSearch.php
locales/English/user.php
locales/English/userRegister.php
register.php
register/processUserForm.php
usercp.php

1. Fix user registration bug that ignored all radio button user options on account creation.
2. Fix multiple styling bugs on user registration
3. Remove page by page styled submit buttons for the new default button
4. Update Register page to add warning to avoid personal information in username and to keep username appropiate.

Various Registration Fixes

---

admin/adminActionsForms.php
admin/adminAdvancedAccessLog.php
admin/adminChatAnalyser.php
admin/adminStatusLists.php
css/desktopOnly/gamepanel.css
css/desktopOnly/global.css
css/gamepanel.css
css/global.css
css/home.css
global/definitions.php
lib/html.php
profile.php

Remove unused css elements
Standardize all site buttons
Fix various formatting issues in code

Css and format Cleanup

---

css/desktopOnly/global.css
css/global.css
global/definitions.php
javascript/clickHandler.js
lib/html.php

Added JS file handles the event listeners and is imported into html.php.

Basic dropdown header, opens and closes on clicks for desktop and mobile 

---

css/desktopOnly/global.css
css/global.css
donations.php
global/definitions.php
lib/html.php
locales/English/developers.php
locales/English/faq.php
locales/English/help.php

Add a donations page
Restyle help page
clean up menu
adjust faq and dev pages
incriment css version

Re-Style Help Pages

---

donations.php

Fix grammar

---

halloffame.php

Creates a tab that displays the hall of fame results but filtered out to users who have logged in during the last 6 months.

Hall of Fame Active Tab

---

admin/adminActions.php

Don't try and reset the min bet if the player was the only person in the game. Since the game will have already been cancelled and will throw an error and stop the loop of the member being removed from games.

Fix Ban Issue

---

install/FullInstall/fullInstall.sql

This is a full install of the base DB with every update that will get a test environement up and running instantly.

Create Full DB Install

---

gamemaster/members.php

Emergency fix

---

gamemaster/game.php

1 reference to a removed function was missed.

Remove dead reference

---

admin/adminActionsRestricted.php
header.php

Fix Mixed Merges

---

admin/adminActionsRestricted.php

fix for fix

---

gamemaster/game.php

Adding requires to function coming up as undefined.

Attempting Bug Fix

---

gamepanel/member.php

This is causing the "units" to show in the wrong spot.

Remove duplicated div

---

css/desktopOnly/global.css
css/global.css
locales/English/user.php
profile.php

Update settings and user search pages with new styling.

Update Form Fields

---

admin/adminActionsRestricted.php
contrib/phpBB3-files/ext/webdip/headerban/event/main_listener.php

Make the new forum pull notices and alerts from the new table.

Change Forum Notice to table

---

contrib/phpBB3-files/ext/webdip/headerban/event/main_listener.php

Phpbb3 again

---

.gitignore
adminInfo.php
lib/html.php

Making an admin only tool for the webdip implementation only. Adding structure and sample file.

Web dip only server tool

---

adminInfoExample.php

Adjusting Git Ignore

---

variants/ClassicChaos/resources/style.css

Made it so that Rumania (which is white now), has a chat box and occupation bar that is black for readability, similar to how Russia is in world.

Fixed Rumania chat color to black

---

contactUsDirect.php
css/desktopOnly/global.css
css/global.css
detailedSearch.php
global/definitions.php
locales/English/gamecreate.php
locales/English/user.php

Mobile css fix

---

admin/adminActions.php
admin/adminActionsForms.php
admin/adminActionsForum.php
admin/adminActionsRestricted.php
admin/adminActionsTD.php
admincp.php
gamepanel/game.php

1. Make game displays cleaner, rewording of game settings in display
2. Clean up Mod tools permissions
3. Fix TD tools display for TD's to have more recent tools like give/take excused missed turns.

Game and Mod Tool Adjustments

---

global/definitions.php
install/1.51-1.52/readme.txt
install/1.51-1.52/update.sql
install/FullInstall/fullInstall.sql

Fixes https://github.com/kestasjk/webDiplomacy/issues/61
Alters wD_Games so that games pot size and minimum bets can now be even larger. Lets see if anyone puts this to use.

Increase max bet to mediumint

---

board.php

The options available to mods were terrible on game view. Updating them to frequently used mod tools and fixing the amazingly broken multi check in games that hasn't been used in a decade to work.

Fix Mod Game Tools

---

css/desktopOnly/global.css
css/global.css
detailedSearch.php
gamelistings.php
global/definitions.php
index.php
lib/html.php
locales/English/intro.php

Rewrote the whole gamelistings page. This includes:
Update styling to match the other recent styling changes on the site.
Rework the paging structure in order to fix several issues with the pager.
Update the game search feature to add options, make options clearer, and fix some broken options like bet.
Updated links to the gamelistings page to be compatible with the new changes.
Fixes the following issues:
https://github.com/kestasjk/webDiplomacy/issues/285
https://github.com/kestasjk/webDiplomacy/issues/152
https://github.com/kestasjk/webDiplomacy/issues/151
https://github.com/kestasjk/webDiplomacy/issues/71
https://github.com/kestasjk/webDiplomacy/issues/68

Game Listings Page

---

detailedSearch.php
gamelistings.php

Fixes url parameter add of phpbb3 and utm stuff. Also changes default to desc.

url fix and desc default

---

css/desktopOnly/global.css

Remove checkbox css that ended up looking awful, that I forgot to delete from desktop only

Fix desktop css

---

gamelistings.php

Include comma's in X - Y of Z results.

Minor Styling Change

---

gamelistings.php
profile.php

Redoes the paging for the profile page.
Redirects the profile search to the gamelisings search page, with parameter userID.
Reworks the gamelistings search page to allow a search with a given userID.
Makes sure that anonymity is not broken in any case.

Profile Paging and Search

---

css/desktopOnly/global.css
css/global.css
gamecreate.php
global/definitions.php
locales/English/gamecreate.php

1. Force gunboat games to be anon.
2. Add ? icon to anon to explain what the selection does and that gunboats default to anon.

Adjust-Game-Create

---

locales/English/tournaments.php

Add clarification on variant type exceptions

Adjust-Tournament-Wording

---

profile.php

Add the length of temp bans for mods to see on the profile.

Profile Add Mod Info

---

board/info/messages.php

Add parenthesis

---

board.php
board/chatbox.php
gamepanel/member.php
gamepanel/memberhome.php

Part of the ongoing Tournament Project. Makes a check to see if you are set as the tournament director for the tournament that this game is a part of, and gives game director powers to you if that is the case.

Check for TD Status and give Game Director powers

---

tournaments.php

Show winners on finished tournaments
Show moderate link on finished tournaments to mods and allowed TD's.

Show Winners

---

profile.php

Update RR text

---

css/desktopOnly/global.css
css/global.css
global/definitions.php
tournaments.php

Style Tournament Pages

---

board.php

Let users unspectate games they are in

---

board/info/messages.php
detailedSearch.php
gamelistings.php
profile.php
tournamentScoring.php

The new paging did not have " " around the values when persisting parameters between pages and sorting. This meant that spaces did not work well with persisting. Fixed that.
Also I fixed some instances else{ that somehow made it past jmo the first time.

Fix paging bug with spaces

---

tournaments.php

Remove draft comments, add useful comments, refactor some of the code.

Tournament Page Cleanup

---

tournamentManagement.php

Adds a list of users and games with links to the tournamentManagement page. Also adds names and links to the add/removal confirmation page. Also adds reasons to failures of adds/removals. Also adds a mod tool which allows mods to sync tournament participants to users in tournament games.

Tourney Mod Stuff

---

profile.php

Update mod contact info, hide mute icons for custom forums.

Update Profile Info

---

locales/English/user.php
usercp.php

Removing unused functionality like Plura and user mutes if a custom forum is set.

Profile and Settings Updates

---

lib/html.php
objects/notice.php
tournamentRegistration.php
tournamentScoring.php
tournaments.php

Creates a tournament registration page which allows users to apply or sign up for tournaments. Tournament Directors can see who has applied with relevant information and choose to accept or reject them. Also allows Tournament Directors to change the status of participants throughout the tournament. Mods also have access to accepting / rejecting / changing status of participants.
When users are accepted / rejected / set to left it will send them a notice.
Also fixed the scoring page to only show accepted or left status participants.

Tournament Registration Page

---

locales/English/tournamentInfo.php

Update tournament rules

---

tournaments.php

Show the number of spectators for a tournament if there are any.

Display tournament spectators

---

tournaments.php

Split ongoing and finished games into different table and display different information for each. Right now it's too hard to see for ongoing tournaments. This also helps simplify the code.

Adjust Tournament Round Games View

---

css/desktopOnly/global.css
css/global.css
global/definitions.php

Make the font smaller to help everything fit on mobile devices.

Adjust Font Size

---

admin/adminMultiFinder.php
css/desktopOnly/global.css
css/global.css
global/definitions.php

adding a new useful adjustment for mods.

Adjust Mod tools

---

admin/adminMultiFinder.php

intentionally leaving non descript cause mod tools.

Another adjustment

---

css/desktopOnly/global.css
css/global.css
global/definitions.php
locales/English/credits.php

Update some of the info on the credits page.

Update Credits Page

---

contactUsDirect.php
donations.php
halloffame.php
locales/English/faq.php
locales/English/help.php
locales/English/intro.php
locales/English/rules.php
variants/AncMed/rules.html

This ought to work now :D
Do tell me if I missed anything (compared to original), but don't think I have.

Typos2 (this ought to work)

---

global/definitions.php

Forgot to update version file, fixing.

Fix Version

---

profile.php

Update the info for RR for better clarity on RR change for live games.

Update Profile Breakdown

---

variants/World/classes/Chatbox.php

World Press Bug

---

contrib/phpBB3-files/ext/webdip/headerban/event/main_listener.php

Make the new forum load the dark mode css files.

Update New Forum

---

index.php

Home page should be restored now

---

locales/English/help.php

HoF is now in the main menu, not needed here anymore.

Remove HoF

---

contactUsDirect.php

Currently a ; instead of a . messing up the text display.

Fix Emergency Pause

---

register.php

Adjust the registration email to be short and to the point.

Update Registration Email

---

register.php

We want new members to know about the discord right away. So adding that info to the registration email.

Adding Discord Link to Registration Email

---

admin/adminActionsRestricted.php

Make a webdip only admin tool to update all donator's on the site to get gold, silver, and bronze ranks. Update the give donator status tools to give the rank as well.

Update Ranks for New Forum

---

admin/adminActionsRestricted.php

Fix Introducted Bug

---

api/responses/unordered_countries.php

- The bot will send orders for games with the oldest process time first

API - Sorting unordered countries by processTime

---

locales/English/user.php

Don't do this when I'm not around

Set dark mode live

---

index.php
lib/html.php

A lot of the code in html and index was oddly formatted, and the recent changes misplaced a javascript function that needs to be moved up for speed of loading.

Fix Code Layout

---

gamepanel/member.php

Allow TD's to see "time last seen" for people in tournament games. Won't work if the TD is in the game.

Adjust TD powers

---

admin/adminActions.php

Cleanup mod tool coding styles to match. Prevent mods from changing bot passwords.

Cleanup Mod tools

---

gamepanel/membershome.php
variants/ClassicChaos/classes/panelMembersHome.php

Any variant >7 players will print on multiple lines on home page

Fix issue 554

---

botgamecreate.php
datc/datcGame.php
gamecreate.php
gamemaster/adjudicator/pregame.php
gamemaster/game.php
global/definitions.php
install/1.60-1.61/readme.txt
install/1.60-1.61/update.sql
install/FullInstall/fullInstall.sql
locales/English/gamecreate.php
objects/game.php
objects/user.php
profile.php

More adjustments for coming change.

Add New Game Type

---

gamemaster/adjudicator/pregame.php
locales/English/gamecreate.php

Fixing 2 bugs from the last push

Fix new game type

---

objects/user.php
profile.php

Change user object to be more effecient.

Change User Object

---

api/responses/unordered_countries.php

- https://webdiplomacy.net/board.php?gameID=246345
- https://webdiplomacy.net/board.php?gameID=246476

API - Only sending orders if turn < 100, to avoid infinite games

---

admin/adminActionsForum.php
admin/adminActionsRestricted.php
admin/adminActionsTD.php
admin/adminLocales.php
admin/adminLog.php
admin/adminStatusLists.php
admin/systemTasks/resetCountryBalancer.php

Disable several of the "clear X" admin tools because they are too dangerous to have live on production sites.
Clean up code to have consistent spacing and styling.

Cleanup Admin Code

---

install/1.57-1.58/update.sql
install/FullInstall/fullInstall.sql

These queries didn't work and were never reverted out of the files.

Fix Sql Files

---

css/darkMode/desktopOnly/global.css
css/darkMode/desktopOnly/home.css
css/darkMode/global.css
css/darkMode/home.css
global/definitions.php
locales/English/credits.php
locales/English/faq.php

FAQ section discusses bots, links to paper. Credit links to Philip's github and paper.

Bot FAQ Section/Credit

---

datc/datcGame.php

Added missing excusedMissedTurns var

---

botgamecreate.php
halloffame.php
objects/notice.php
objects/silence.php

Minor updates and prevent possible incorrect country code from being pushed on bot game create

code updates and minor bug fix

---

gamepanel/game.php

The lock icon was hidden by mistake in the last push. Adding it back.

Add lock icon back

---

admin/adminActions.php

Allow mods to generate email registration links when the email doesn't send or ends up in spam.

Add New Mod Tool

---

gamecreate.php

The checks on the new game feature were blocking games with phases over 25 hours. Fixing and cleaning up some of the other logic.

Fix Game Creation

---

admin/adminActionsRestricted.php
global/definitions.php
install/1.62-1.63/readme.txt
install/1.62-1.63/update.sql
install/FullInstall/fullInstall.sql
profile.php

Allows admins to change a player's username, creates table wD_UsernameHistory

Add new admin tool

---

admin/adminMultiFinder.php
lib/time.php

Reverts kestasjk/webDiplomacy#667

Revert "Fix maf bug"

---

admin/adminActionsRestricted.php
global/definitions.php
install/1.63-1.64/readme.txt
install/1.63-1.64/update.sql
install/FullInstall/fullInstall.sql
profile.php

Creates tool to allow admins to change registered emails and creates table to store changed emails for moderator case reference

New admin tool

---

admin/adminAdvancedAccessLog.php
gamemaster/game.php
gamepanel/game.php
locales/English/gamecreate.php

Fixes 2 display bugs with the new changing phase lengths feature, and prevents the feature from updating some columns in the wD_Games table for debugging purposes. Various stylistic code cleanup as well.

Fix Various Live Game Problems

---

profile.php

Fixed some reliability-related spelling errors and grammar inconsistencies.

Fixed spelling errors and grammar

---

install/FullInstall/fullInstall.sql

Fix syntax error in fullInstall.php

---

ghostratings/calculations.php

fix a big involving known world

small change on gr initialization

---

gamemaster/adjudicator/pregame.php
header.php
map/drawMap.php
register/processUserForm.php

Update with various php 7+ Kestas made on the server.

Update Git to Match Server

---

css/darkMode/desktopOnly/global.css
css/darkMode/global.css
css/desktopOnly/global.css
css/global.css
doc/javascript.txt
gamelistings.php
global/definitions.php
index.php
javascript/help.js
lib/html.php
locales/English/gamecreate.php
register/processUserForm.php
usercp.php

• Renders modal on home page, game creation form, game listings, and account settings for new users based on cookies expiring after 365 days
• Adds helper functions for modal operations
• libHTML function can be reused for later help modal additions

Tutorial mode for newly registered users

---

css/darkMode/desktopOnly/global.css
css/darkMode/global.css
css/desktopOnly/global.css
css/global.css
lib/html.php
userprofile.php

This is an alpha for the page that will eventually replace the exisiting profile page. This page will be designed for sites that have gotten rid of the built in forum, the old profile page will be left intact for vDip or other implimentations that do not have a custom forum.

Publish a mod only Alpha View New Profile

---

css/darkMode/desktopOnly/global.css
css/darkMode/global.css
css/desktopOnly/global.css
css/global.css
global/definitions.php
lib/html.php
objects/user.php
search.php
userprofile.php

Adding google charting
Adding GR data
removing L_t for translations, this page is intended for phpbb3/new forum users only, old profile being left for other installments.
pulling search out of profile page and into a new page

Updates to new profile

---

admin/adminAdvancedAccessLog.php
admin/adminMultiFinder.php
admin/adminStatusLists.php
contactUsDirect.php
detailedSearch.php
gamepanel/member.php
gamepanel/members.php
halloffame.php
index.php
lib/html.php
locales/English/credits.php
locales/English/points.php
objects/member.php
objects/user.php
tournamentManagement.php
tournamentRegistration.php
tournamentScoring.php
tournaments.php
userprofile.php

Replacing the links to the old profile throughout the site.

Final Changes For New Profile

---

css/darkMode/desktopOnly/global.css
css/darkMode/global.css
css/desktopOnly/global.css
css/global.css
ghostRatings.php
global/definitions.php
javascript/locales/ghostRatings.js
locales/English/faq.php
locales/English/ghostRatings.php
locales/English/intro.php

• Adds new GR Explained page, associated JS script
• Reformats and improves Intro.php
• Updates AI and GR sections in FAQ

Adds GR Explained page

---

lib/html.php
userprofile.php

Adjust moderator only permissions from initial testing

Additional fixes

---

halloffame.php

Correct HOF

---

api/responses/game_state.php
api/responses/message.php
lib/gamemessage.php

Added game message phase marker

Added game message phase marker

---

install/1.66-1.67/update.sql

Bug fix for update SQL

---

install/FullInstall/fullInstall.sql

Fixes a double SQL operation in Full Install SQL script: the script was not able to run because of doubled scripts

Fix fullInstall.sql

---

gamemaster/adjudicator/pregame.php
gamepanel/game.php

My two first commits to webDip

Spectators counter and "Game started" message

---

gamemaster/adjudicator/pregame.php
gamepanel/game.php

Reverts kestasjk/webDiplomacy#759

Revert "Spectators counter and "Game started" message"

---

gamemaster/game.php
objects/game.php

Checked in this missing function; not sure how I missed it.
I haven't really tested it beyond checking it doesn't crash. This should only affect grace periods.

Check in getMinPhaseMinutes

---

admin/adminActionsRestricted.php
docker-compose.yml
gamepanel/gameboard.php
group.php
install/1.70-1.71/update.sql
lib/message.php
objects/group.php
objects/groupUser.php
objects/member.php
userprofile.php

Restored webserver to docker config, button for easily adding users for test purposes, support for groups in anonymous games

Support for groups / suspicion reporting in anonymous games

---

ajax.php
composer.json
composer.lock
config.sample.php
group.php
install/1.70-1.71/update.sql
install/FullInstall/fullInstall.sql
lib/auth.php
lib/sms.php
locales/English/user.php
objects/group.php
objects/user.php
usercp.php

Added the ability to link user accounts to a mobile phone number via Twilio SMS integration

Phone SMS user account linking
